version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:github-actions)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"

  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:server)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"

  - package-ecosystem: "pip"
    directory: "/server/db"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:server-db)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"

  - package-ecosystem: "pip"
    directory: "/bot"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:bot)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:docker)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"

  - package-ecosystem: "docker"
    directory: "/docker/bot"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:dockerfile-bot)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"

  - package-ecosystem: "docker"
    directory: "/docker/server"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:dockerfile-server)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"
